title = "Nina Zakharenko"
baseURL = "https://nnja.io"
theme = "bilberry-hugo-theme"

enableRobotsTXT = true

# Change to your content language. Supported values: en, de, es, fr, ru
DefaultContentLanguage = "en"

# Enable / Disable Google Analytics statistics for your site
googleAnalytics = ""

# Enable / Disable comments on the articles via Disqus.
disqusShortname = "bilberry-hugo-theme"

[params]
  # Favicon for the browser's favorites and tabs
  favicon = "" # set a favicon icon

  # Custom CSS / JS modules that will be imported by the template.
  # Files are relative to the static/ directory or a URL.
  # Files are imported in the order they appear here, after
  # theme.css and theme.js, respectively.
  css_modules = []
  js_modules = []

  # Description and meta data for the search engines
  author = "Nina Zakharenko"
  description = "Blog of Nina Zakharenko - Python Deverloper, Azure Cloud Developer Advocate, works for Microsoft"
  keywords = "blog, technology, python, pythonista, programming, developer, software developer, software engineer, azure, cloud, cloud computing, testing, clean code"

  # How many articles should be displayed at once?
  paginate = 10

  # Enable / Disable MathJax
  enable_mathjax    = false

  # Enable / Disable algolia search
  algolia_search    = true
  algolia_appId     = "Y2C4RWMPXW"
  algolia_apiKey    = "50ea7f8c41c0ad233926e0be2b769ed1"
  algolia_indexName = "default-content"

  # Header configuration
    # your subtitle if you want to use any
    subtitle = "Developer, Pythonista, Speaker. Cloud Developer Advocate @ Microsoft"

    # if you want to use gravatar for the header image
    gravatarEMail = ""

    # set an path to the image file you want to use | overwrites gravatar
    customImage = "https://pbs.twimg.com/profile_images/944270517208358912/nU9hjc4n_400x400.jpg"

    # always display the top navigation (with pages and search) on non-mobile screens
    permanentTopNav = true

    # credits line configuration
    copyrightBy = "by Nina Zakharenko"
    copyrightUseCurrentYear = true  # set to true to always display the current year in the copyright
    copyrightYearOverride = "2017"
    copyrightUrl = "https://github.com/Lednerb"
    creditsText = "Bilberry Hugo Theme"
    creditsUrl = "https://github.com/Lednerb/bilberry-hugo-theme"

  # social media profile urls for the footer links
  facebook   = ""
  twitter    = "https://twitter.com/nnja"
  googleplus = ""
  pinterest  = ""
  instagram  = "https://instagram.com/nnjas"
  tumblr     = ""
  youtube    = ""
  vimeo      = ""
  github     = "https://github.com/nnja"

# don't change anything here
[taxonomies]
  author   = "author"
  tag      = "tags"
  category = "categories"

[outputs]
  home = [ "HTML", "JSON" ]
  page = [ "HTML" ]
